<?php


// calculating the distance between two lat/long points
function distance($a, $b)
{
    list($lat1, $lon1) = $a;
    list($lat2, $lon2) = $b;

    $theta = $lon1 - $lon2;
    $dist = sin(deg2rad($lat1)) * sin(deg2rad($lat2)) +  cos(deg2rad($lat1)) * cos(deg2rad($lat2)) * cos(deg2rad($theta));
    $dist = acos($dist);
    $dist = rad2deg($dist);
    $miles = $dist * 60 * 1.1515;
    return $miles;
}





function closest_store_menu(){
	$items['closest/store'] = array(
		'page callback' => 'closest_store',
		'page arguments' => array(2,3),
		'access arguments' => array('access content')
		);
	return $items;

}

function closest_store($lat,$long){
	// current position of the device with gps 
	$ref = array($lat,$long);

 // list containig the stores iformation ** hardcoded to be replaced
	$items = array(
	    '0' => array('Casablanca','otheritem1details....','33.513919','-7.459717'),
	    '1' => array('khribga','otheritem1details....','32.861132','-6.888428'),
	    '2' => array('morenear','otheritem1details....','33.728908','-7.303162'),
	    '3' => array('item4','otheritem1details....','33.645645','-42.5323'),
	);

	$distances = array_map(function($item) use($ref) {
	    $a = array_slice($item, -2);
	    return distance($a, $ref);
	}, $items);

	asort($distances);
	$json_output = drupal_json_output($items[key($distances)]);
	drupal_exit();
	return $json_output;
}